### ISSUE TITLE
"Pool shutdown unexpectedly" on client connection pool

### ISSUE THREAD

**Issue by raboof** [apache/pekko-http#587]
Getting a `Pool shutdown unexpectedly` error when gracefully stopping the actor system. We should probably document what can trigger this in https://pekko.apache.org/docs/pekko-http/current/troubleshooting ?
```
[my-system-pekko.actor.default-dispatcher-23] INFO org.apache.pekko.actor.CoordinatedShutdown - Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
Aug 19 15:05:14 server generate-stats-start[1196329]: [ERROR] [08/19/2024 15:05:14.645] [my-system-pekko.actor.default-dispatcher-6] [pekko://my-system/system/pool-master] connection pool for Pool(shared->https://purchase.izettle.com:443) has shut down unexpectedly
Aug 19 15:05:14 server generate-stats-start[1196329]: java.lang.IllegalStateException: Pool shutdown unexpectedly
Aug 19 15:05:14 server generate-stats-start[1196329]:         at org.apache.pekko.http.impl.engine.client.PoolInterface$Logic.postStop(PoolInterface.scala:224)
Aug 19 15:05:14 server generate-stats-start[1196329]:         at org.apache.pekko.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:614)
```
AFAICT I've consumed all response entities.

(the code is at https://codeberg.org/eicas/admin-sync/src/branch/main/Zettle.scala - warning, quick hacks ahead :) )

**Comment by jtjeferreira** [comment]
> AFAICT I've consumed all response entities.

In this code https://codeberg.org/eicas/admin-sync/src/branch/main/Zettle.scala#L62-L63 

```scala
if (r.status != StatusCodes.OK)
  throw new IllegalStateException(s"Zettle returned status ${r.status}")
```

you are not consuming the response, if the status is not OK...
